"""Adicionado Tabelas

Revision ID: 61bcd69467c2
Revises: 7aa743ac748a
Create Date: 2021-06-23 19:46:49.543786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bcd69467c2'
down_revision = '7aa743ac748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('tamanhos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanhos', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
