"""Adicionado Tabelas

Revision ID: 7aa743ac748a
Revises: 8167fb30d556
Create Date: 2021-06-23 19:45:37.180549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa743ac748a'
down_revision = '8167fb30d556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
